name: Go Backup Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.2"

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Create Backup Archive
        run: tar -czvf menumakanan_backup.tar.gz .

      - name: Upload Backup Artifact
        uses: actions/upload-artifact@v3
        with:
          name: menumakanan-backup
          path: menumakanan_backup.tar.gz
